"""add timing to cv_draft

Revision ID: 129f21ad6b02
Revises: 41cf713058ae
Create Date: 2026-09-09 10:10:09.154159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129f21ad6b02'
down_revision: Union[str, Sequence[str], None] = '41cf713058ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_draft', sa.Column('timing', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_draft', 'timing')
    # ### end Alembic commands ###
