"""add cv_draft table

Revision ID: 206644e029cd
Revises: 270c25eb93a8
Create Date: 2026-08-03 23:20:17.334592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required by sqlmodel.sql.sqltypes.AutoString() below


# revision identifiers, used by Alembic.
revision: str = '206644e029cd'
down_revision: Union[str, Sequence[str], None] = '270c25eb93a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_draft',
    sa.Column('candidate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vacancy', sa.JSON(), nullable=False),
    sa.Column('assembled_cv', sa.JSON(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_draft')
    # ### end Alembic commands ###
