"""add evidence locked fields

Revision ID: 270c25eb93a8
Revises: c0c0928f0aa2
Create Date: 2026-08-03 15:15:52.107141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required by sqlmodel.sql.sqltypes.AutoString() below


# revision identifiers, used by Alembic.
revision: str = '270c25eb93a8'
down_revision: Union[str, Sequence[str], None] = 'c0c0928f0aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not part of the autogenerate output):
    # SQLite rejects a NOT NULL column added to a non-empty table without
    # one, and this table already has real rows (docs/development_plan.md
    # Phase 13's committed profiles) — matches Evidence.locked's own
    # `default=False` on the Pydantic side.
    op.add_column(
        'evidence', sa.Column('locked', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column('evidence', sa.Column('locked_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'locked_text')
    op.drop_column('evidence', 'locked')
    # ### end Alembic commands ###
