"""Deterministically merges a Candidate Profile with a vacancy-tailored
CVProjection into a complete, ATS-structured AssembledCV.

Per docs/architecture.md's "LLM never returns 'final CV text'" principle:
identity, contact info, education, dates, company names, languages,
certifications, and Key Projects are facts and are copied straight from the
Candidate Profile here — never regenerated by an LLM. Only the
summary/bullets in CVProjection are freely AI-authored; skills/technologies
are AI-*ranked* (see _rank_by_category), not authored — their membership
always comes from the Candidate Profile. See docs/development_plan.md
Phase 5 notes.

Employment gaps (Experience.is_gap=True — parental leave, sabbatical, career
break) are also facts, not tailorable content: they never have supporting
Evidence, so a CVProjection will never reference them. They're always
included here regardless, in the Candidate's own order, so an unexplained
gap in the timeline never silently disappears from the exported CV.
"""

from __future__ import annotations

from typing import TypeVar

from app.errors import ValidationError
from domain.models import (
    AssembledCV,
    AssembledExperienceEntry,
    Candidate,
    CVProjection,
    Skill,
    TailoredBullet,
    TailoredExperience,
    Technology,
)

# Skill and Technology are shape-identical for ranking purposes (name +
# category); shared here rather than duplicated, same reasoning as
# ui/graph_explorer.py's _summarize_skill_like/_ENTITY_SPECS reuse.
_TCategorized = TypeVar("_TCategorized", Skill, Technology)


def _rank_by_category(
    candidate_items: list[_TCategorized], ranked_names: list[str]
) -> list[_TCategorized]:
    """Groups `candidate_items` (Candidate.skills or Candidate.technologies)
    by category — in their own first-appearance order, never AI-decided,
    so an item's category membership is never at risk from the LLM
    inventing/omitting one — then, within each category, sorts by the
    item's position in `ranked_names` (the Bullet Rewriting stage's
    relevance ranking of every name, see prompts/05_rewrite_bullets_v1.md).
    An item `ranked_names` doesn't mention sorts after every item it does
    mention, within that same category — never dropped. A name in
    `ranked_names` matching no `candidate_items` entry (the LLM invented
    one despite being told not to) is simply never looked up here —
    harmless, ignored.
    """
    rank = {name.strip().lower(): index for index, name in enumerate(ranked_names)}
    unranked = len(ranked_names)

    categories: dict[str | None, list[_TCategorized]] = {}
    for item in candidate_items:
        categories.setdefault(item.category, []).append(item)

    ordered: list[_TCategorized] = []
    for members in categories.values():
        members.sort(key=lambda item: rank.get(item.name.strip().lower(), unranked))
        ordered.extend(members)
    return ordered


def build_untailored_projection(candidate: Candidate) -> CVProjection:
    """Zero-AI `CVProjection` — the "export without tailoring" path (CV
    export screen): every non-gap role's own bullets verbatim, Skills/
    Technologies in their own original order. Fed straight into
    `assemble_cv()` exactly like a real LLM-produced `CVProjection` would
    be, so it produces a complete `AssembledCV` with no LLM call at all.

    Gap entries need no entry in the returned `experience` list —
    `assemble_cv()` already includes them unconditionally regardless of
    what `CVProjection.experience` contains, same as for a real tailored
    projection.

    Passing each list's own names as `_rank_by_category`'s `ranked_names`
    (see `assemble_cv()`) makes that reorder a no-op: every item's rank
    equals its own original position, so category grouping stays exactly
    as it is in the Candidate Profile — nothing gets reordered by
    "relevance" the way a real tailoring pass would.
    """
    experience: list[TailoredExperience] = []
    for exp in candidate.experience:
        if exp.is_gap:
            continue
        bullets = [
            TailoredBullet(text=text) for text in [*exp.responsibilities, *exp.achievements]
        ]
        for project in exp.projects:
            bullets.extend(
                TailoredBullet(text=text, project=project.name)
                for text in [*project.responsibilities, *project.achievements]
            )
        experience.append(TailoredExperience(experience_id=exp.id, bullets=bullets))

    return CVProjection(
        summary=candidate.summary or "",
        experience=experience,
        skills=[s.name for s in candidate.skills if not s.is_category_header],
        technologies=[t.name for t in candidate.technologies if not t.is_category_header],
    )


def assemble_cv(candidate: Candidate, projection: CVProjection) -> AssembledCV:
    """Build the final exportable CV from a Candidate + a CVProjection.

    `headline` prefers `projection.headline` (Bullet Rewriting's own
    vacancy-tailored one, Post-4.10 follow-up) and falls back to
    `candidate.headline` only when the projection didn't set one — true for
    `build_untailored_projection`'s zero-AI path, which deliberately leaves
    every profile fact as-is.

    Experience entries are emitted in the Candidate's own order (typically
    reverse-chronological, as parsed from the resume) — NOT the order
    CVProjection lists them in, since a resume's timeline should read
    chronologically, not by AI-assessed relevance to this vacancy.

    Every Candidate.experience entry is always included — never just the
    ones `projection.experience` references:
    * `is_gap=True` entries (career breaks, parental leave, ...) always get
      `bullets=[]` — they're facts, never AI-tailored.
    * Other entries use `projection.experience`'s bullets when the LLM
      referenced their id; when it didn't, they still appear with
      `bullets=[]` (company/position/period only, no achievements) rather
      than disappearing from the CV entirely. A role vanishing outright
      used to be exactly what happened here — reported directly, from a
      real tailored export where an early-career role the LLM judged not
      relevant enough for this vacancy came out looking like an
      unexplained employment gap, understating the candidate's actual
      years of experience. `is_gap` entries already got this "always show
      the fact, even with nothing to say about it" treatment; this makes
      every entry consistent with that, not just gaps.

    Raises ValidationError if `projection.experience` references an
    experience_id that isn't in the Candidate at all (a stale or
    hallucinated id — a signal something's wrong upstream, not something to
    silently drop).
    """
    known_ids = {exp.id for exp in candidate.experience}
    unknown_ids = sorted({t.experience_id for t in projection.experience} - known_ids)
    if unknown_ids:
        raise ValidationError(
            f"CVProjection references unknown experience_id(s) {unknown_ids!r} "
            "— not found in the Candidate Profile."
        )

    tailored_by_id = {t.experience_id: t for t in projection.experience}

    entries: list[AssembledExperienceEntry] = []
    for exp in candidate.experience:
        # Facts, not AI-tailored content — see AssembledExperienceEntry's
        # own docstring for why this is keyed by project *name* rather than
        # living on each TailoredBullet.
        project_urls = {project.name: project.url for project in exp.projects if project.url}

        if exp.is_gap:
            entries.append(
                AssembledExperienceEntry(
                    experience_id=exp.id,
                    company=exp.company,
                    company_url=exp.company_url,
                    position=exp.position,
                    period=exp.period,
                    location=exp.location,
                    bullets=[],
                    is_gap=True,
                    project_urls=project_urls,
                )
            )
            continue

        tailored = tailored_by_id.get(exp.id)
        entries.append(
            AssembledExperienceEntry(
                experience_id=exp.id,
                company=exp.company,
                company_url=exp.company_url,
                position=exp.position,
                period=exp.period,
                location=exp.location,
                bullets=tailored.bullets if tailored is not None else [],
                is_gap=False,
                project_urls=project_urls,
            )
        )

    return AssembledCV(
        name=candidate.name,
        language=candidate.language,
        headline=projection.headline or candidate.headline,
        employment_types_sought=candidate.employment_types_sought,
        contacts=candidate.contacts,
        summary=projection.summary,
        experience=entries,
        volunteer_experience=candidate.volunteer_experience,
        education=candidate.education,
        skills=_rank_by_category(
            [s for s in candidate.skills if not s.is_category_header], projection.skills
        ),
        technologies=_rank_by_category(
            [t for t in candidate.technologies if not t.is_category_header], projection.technologies
        ),
        languages=candidate.languages,
        certifications=candidate.certifications,
        awards=candidate.awards,
        projects=candidate.projects,
        publications=candidate.publications,
        portfolio_links=candidate.portfolio_links,
    )
